Improve warnings & error messages.
Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/script/_setup_script b/script/_setup_script
--- a/script/_setup_script
+++ b/script/_setup_script
@@ -37,6 +37,6 @@ unset WORDCHARS
 mas_dir="${0:a:h:h}"
 
 if ! cd -- "${mas_dir}"; then
-	printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+	printf $'Error: Failed to cd into mas directory: %s\n' "${mas_dir}" >&2
 	exit 1
 fi
