`cd` into root of mas project at beginning of every bash script.
Partial #638

Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/script/bottle b/script/bottle
--- a/script/bottle
+++ b/script/bottle
@@ -14,7 +14,14 @@
 # Variables
 #
 
-BUILD_DIR="${PWD}/.build"
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
+BUILD_DIR=.build
 BOTTLE_DIR="${BUILD_DIR}/bottles"
 CORE_TAP_PATH="$(brew --repo homebrew/core)"
 MAS_VERSION="$(script/version)"
diff --git a/script/clean b/script/clean
--- a/script/clean
+++ b/script/clean
@@ -6,5 +6,12 @@
 # Deletes the build directory.
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 swift package clean
 swift package reset
diff --git a/script/package b/script/package
--- a/script/package
+++ b/script/package
@@ -6,7 +6,14 @@
 # Builds macOS installer component and distribution packages.
 #
 
-BUILD_DIR="${PWD}/.build"
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
+BUILD_DIR=.build
 COMPONENT_PACKAGE="${BUILD_DIR}/mas_components.pkg"
 DISTRIBUTION_PACKAGE="${BUILD_DIR}/mas.pkg"
 
@@ -17,7 +24,7 @@ IDENTIFIER="com.mphys.mas-cli"
 DISTRIBUTION_PLIST="Package/Distribution.plist"
 
 # Destination for install root
-DSTROOT=.build/distributions
+DSTROOT="${BUILD_DIR}/distributions"
 script/install "${DSTROOT}/usr/local" --universal
 
 MAS_VERSION="$(script/version)"
diff --git a/script/uninstall b/script/uninstall
--- a/script/uninstall
+++ b/script/uninstall
@@ -6,6 +6,13 @@
 # Removes mas from PREFIX.
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 # Override default prefix path with optional 1st arg
 PREFIX="${1:-"$(brew --prefix)"}"
 
diff --git a/script/update_headers b/script/update_headers
--- a/script/update_headers
+++ b/script/update_headers
@@ -6,6 +6,13 @@
 # Runs class-dump to generate headers for Apple private frameworks.
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 main() {
   check_class_dump
   extract_private_framework_headers "CommerceKit"
