`cd` into root of mas project at beginning of every bash script.
Partial #638

Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/script/brew_core_update b/script/brew_core_update
--- a/script/brew_core_update
+++ b/script/brew_core_update
@@ -9,11 +9,17 @@
 # brew bump-formula-pr --help
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 CORE_TAP_PATH="$(brew --repo homebrew/core)"
 CORE_MAS_FORMULA_FILE="${CORE_TAP_PATH}/Formula/m/mas.rb"
 
-PROJECT_PATH="$(git rev-parse --show-toplevel)"
-LOCAL_MAS_FORMULA_PATH="${PROJECT_PATH}/Homebrew/mas.rb"
+LOCAL_MAS_FORMULA_PATH=Homebrew/mas.rb
 
 function usage {
   echo "Usage: brew_core_update [-d] [<version_tag> [<sha1_hash>]]"
diff --git a/script/brew_release_validate b/script/brew_release_validate
--- a/script/brew_release_validate
+++ b/script/brew_release_validate
@@ -7,6 +7,13 @@
 # https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-contribute-a-fix-to-the-foo-formula
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 brew uninstall --force mas
 brew install --build-from-source mas
 brew test mas
diff --git a/script/brew_tap_update b/script/brew_tap_update
--- a/script/brew_tap_update
+++ b/script/brew_tap_update
@@ -7,6 +7,13 @@
 # https://github.com/mas-cli/homebrew-tap/blob/main/Formula/mas.rb
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 function usage {
   echo "Usage: brew_tap_update [<version_tag> [<sha1_hash>]]"
   echo "  version will be inferred using version script if not provided"
diff --git a/script/build_artifacts b/script/build_artifacts
--- a/script/build_artifacts
+++ b/script/build_artifacts
@@ -6,6 +6,13 @@
 # Runs all related scripts for generating all artifacts.
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 MAS_VERSION="$(script/version)"
 
 echo "Building mas ${MAS_VERSION} artifacts"
diff --git a/script/package_install b/script/package_install
--- a/script/package_install
+++ b/script/package_install
@@ -6,6 +6,13 @@
 # Installs the mas distribution package. Requires sudo access.
 #
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 IDENTIFIER=com.mphys.mas-cli
 
 echo "==> 📲 Installing mas"
