Write to stderr where appropriate.
Partial #638

Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/script/format b/script/format
--- a/script/format
+++ b/script/format
@@ -21,7 +21,7 @@ printf $'==> 🚨 Formatting mas\n'
 
 for LINTER in markdownlint prettier shfmt swift-format swiftformat swiftlint yamllint; do
   if [[ ! -x "$(command -v "${LINTER}")" ]]; then
-    printf $'error: %s is not installed. Run \'script/bootstrap\' or \'brew install %s\'.\n' "${LINTER}" "${LINTER}"
+    printf $'error: %s is not installed. Run \'script/bootstrap\' or \'brew install %s\'.\n' "${LINTER}" "${LINTER}" >&2
     exit 1
   fi
 done
