Rename `linter` as `formatter` in `script/format`.
Partial #638

Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/script/format b/script/format
--- a/script/format
+++ b/script/format
@@ -17,9 +17,9 @@ fi
 
 printf $'==> 🚨 Formatting mas %s\n' "$(script/version)"
 
-for linter in markdownlint prettier shfmt swift-format swiftformat swiftlint yamllint; do
-  if [[ ! -x "$(command -v "${linter}")" ]]; then
-    printf $'error: %s is not installed. Run \'script/bootstrap\' or \'brew install %s\'.\n' "${linter}" "${linter}" >&2
+for formatter in markdownlint prettier shfmt swift-format swiftformat swiftlint yamllint; do
+  if [[ ! -x "$(command -v "${formatter}")" ]]; then
+    printf $'error: %s is not installed. Run \'script/bootstrap\' or \'brew install %s\'.\n' "${formatter}" "${formatter}" >&2
     exit 1
   fi
 done
