Improve scripts: bootstrap, build, format, lint, test & version.
Allow them to be run from any directory.

Call version from lint & test to create Package.swift with version info.

Fail when accessing unset variables.

Improve variable names.

Fix lint issues.

Improve lint & format scripts.

Don't require user input to continue linting.

Much cleaner lint output.

Reorder lint output.

Get swift-format from Brewfile instead of from Package.swift:

 - Speeds up linting.
 - Properly models dependency (not a code dependency).
 - swift-format depends on an old version of swift-argument-parser. Will refactor to use SAP soon.

Include some improvements from 1.8.7 PR.

Other scripts need improvement, too.

Resolve #545

Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash -eu
 #
 # script/test
 # mas
@@ -6,5 +6,13 @@
 # Runs mas tests.
 #
 
-echo "==> ✅ Testing"
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
+printf $'==> ✅ Testing mas (%s)\n' "$(script/version)"
+
 swift test
diff --git a/script/version b/script/version
--- a/script/version
+++ b/script/version
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash -eu
 #
 # script/version
 # mas
@@ -9,12 +9,17 @@
 # This no longer works with MARKETING_VERSION build setting in Info.plist
 # agvtool what-marketing-version -terse1
 
+mas_dir="$(readlink -fn "$(dirname "${BASH_SOURCE:-"${0}"}")/..")"
+
+if ! cd -- "${mas_dir}"; then
+  printf $'Error: Could not cd into mas directory: %s\n' "${mas_dir}" >&2
+  exit 1
+fi
+
 VERSION=$(git describe --abbrev=0 --tags)
 VERSION=${VERSION#v}
 
-SCRIPT_PATH=$(dirname "$(which "$0")")
-
-cat <<EOF >"${SCRIPT_PATH}/../Sources/MasKit/Package.swift"
+cat <<EOF >"Sources/MasKit/Package.swift"
 // Generated by: script/version
 enum Package {
     static let version = "${VERSION}"
