Rename `directory` & `dir` as `folder` in scripts.
Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/Scripts/_setup_script b/Scripts/_setup_script
--- a/Scripts/_setup_script
+++ b/Scripts/_setup_script
@@ -36,10 +36,10 @@ unset KEYBOARD_HACK
 unset TMPSUFFIX
 unset WORDCHARS
 
-mas_dir="${0:A:h:h}"
+mas_folder="${0:A:h:h}"
 
-if ! cd -- "${mas_dir}"; then
-	printf $'Error: Failed to cd into mas directory: %s\n' "${mas_dir}" >&2
+if ! cd -- "${mas_folder}"; then
+	printf $'Error: Failed to cd into mas folder: %s\n' "${mas_folder}" >&2
 	exit 1
 fi
 
