Spacing in `tag-pushed.yml`.
Partial #638

Signed-off-by: Ross Goldberg <484615+rgoldberg@users.noreply.github.com>

diff --git a/.github/workflows/tag-pushed.yml b/.github/workflows/tag-pushed.yml
--- a/.github/workflows/tag-pushed.yml
+++ b/.github/workflows/tag-pushed.yml
@@ -29,9 +29,9 @@ jobs:
       - name: 🖋 Delete tag lacking valid signature
         run: |
           git fetch --tags --force
-          if [[ \
-          "$(git cat-file tag "${GITHUB_REF_NAME}")" != *'-----BEGIN SSH SIGNATURE-----'*'-----END SSH SIGNATURE-----' \
-          ]]; then
+          if [[\
+           "$(git cat-file tag "${GITHUB_REF_NAME}")" != *'-----BEGIN SSH SIGNATURE-----'*'-----END SSH SIGNATURE-----'\
+           ]]; then
             printf $'Error: Deleting tag %s because it does not have a valid signature\n' "${GITHUB_REF_NAME}" >&2
             git push -d origin "${GITHUB_REF_NAME}"
             exit 1
@@ -50,8 +50,8 @@ jobs:
         run: |
           git fetch --force origin "${DEFAULT_BRANCH_NAME}:${DEFAULT_BRANCH_NAME}"
           if ! git merge-base --is-ancestor "${GITHUB_REF_NAME}" "${DEFAULT_BRANCH_NAME}"; then
-            printf $'Error: Deleting version tag %s because it is not on the %s branch\n' "${GITHUB_REF_NAME}" \
-              "${DEFAULT_BRANCH_NAME}" >&2
+            printf $'Error: Deleting version tag %s because it is not on the %s branch\n' "${GITHUB_REF_NAME}"\
+             "${DEFAULT_BRANCH_NAME}" >&2
             git push -d origin "${GITHUB_REF_NAME}"
             exit 3
           fi
@@ -78,12 +78,12 @@ jobs:
           HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
         run: |
           brew tap mas-cli/tap
-          brew bump-formula-pr \
-            --tag "${GITHUB_REF_NAME}" \
-            --revision "${GITHUB_SHA}" \
-            --no-fork \
-            --no-browse \
-            --online \
-            --strict \
-            --verbose \
-            mas-cli/tap/mas
+          brew bump-formula-pr\
+           --tag "${GITHUB_REF_NAME}"\
+           --revision "${GITHUB_SHA}"\
+           --no-fork\
+           --no-browse\
+           --online\
+           --strict\
+           --verbose\
+           mas-cli/tap/mas
